sudo: required

language: node_js
node_js:
  - "8.4.0"

addons:
  sauce_connect: true

before_script:
    # - docker-compose up --build -d
    - node index.js &
    - sleep 3

script:
  - curl http://localhost:8080
  - npm run e2e
